### PR TITLE
SF2: Fix loop offsets + tuning

### LINKED ISSUE #80: SF2: Incorrect loop indexes & Realtime: Missed note off events
As the title says, the buffer does not seem to drop notes that have been played, and seems to get stuck playing them over and over again?

XSynth is the *only* engine that does not make use of OMv2's internal events buffer, instead it gets fed the events directly, so this is 100% an issue outside of OMv2.

https://github.com/user-attachments/assets/87ad214c-7b9c-4a21-9db4-81a8a16b4a3a

### PR DESCRIPTION
**Pull request by MyBlackMIDIScore**
Added the coarse offset and looping SF2 zones and fixed support for loop offsets and fine/coarse tuning.

Should fix #80

### CODE REVIEW

**Comment by MyBlackMIDIScore** [comment]
Why did clippy just remember those unused functions wtf

**Review by arduano — APPROVED** [review]
idk what the implementation details are but lgtm

**Comment by arduano** [comment]
I'll figure out clippy

**Comment by MyBlackMIDIScore** [comment]
> idk what the implementation details are but lgtm

I only added support for some SF2 generators (equivalent of opcodes for SFZ) and how some existing ones were parsed because it was wrong. I tested it and it works fine so dw

> I'll figure out clippy

Should I wait for your PR about clippy to be merged or are you going to do it afterwards?

**Comment by arduano** [comment]
Weird, I wonder why the changes of my last PR show up in this PR as well

**Comment by MyBlackMIDIScore** [comment]
> Weird, I wonder why the changes of my last PR show up in this PR as well

I merged master in sf2-fixes before merging this PR to avoid conflicts, so it shows your commits here. Although in master it doesn't show that I wrote any of your changes so it's all good.

**Comment by arduano** [comment]
Yeah usually github is supposed to hide duplicate changes from PRs, it's not supposed to show master's changes in your branch when you update from master, kinda strange but oh well

**Pull request merged**
