### PR TITLE
Update soundfont-rs to 0.1

### PR DESCRIPTION
**Pull request by PolyMeilex**
Just a simple dep update.

`soundfont-rs` can now handle non-spec compliant files a lot more gracefully, now it's up to the user to decide what to do with custom generators, in this MR I simply ignore them. 

It should also be faster at parsing the files, as it no longer allocates memory per RIFF chunk read, instead it has a single scratch buffer allocation for the whole parsing step.

### CODE REVIEW

**Comment by arduano** [comment]
oh I love having an unpinned cargo nightly
I'll fix in a sec

**Comment by arduano** [comment]
Merged my fix, update from master please

**Comment by arduano** [comment]
Strange, can you please update from master?

**Comment by PolyMeilex** [comment]
Oh yeah, we all love the wonders of unpinned Clippy :smile: 
Thanks.

**Pull request merged**
